extensions: {}
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  World:
    filename: src/World.hs
  Physics:
    filename: src/Physics.hs
  Main(src/Main.hs):
    target-type: web
    filename: src/Main.hs
  Json:
    filename: src/Json.hs
  Test.Main:
    target-type: console
    filename: src/Test/Main.hs
  Simulation:
    filename: src/Simulation.hs
