extensions: {}
files:
  World: src/World.hs
  Physics: src/Physics.hs
  Json: src/Json.hs
  Main: src/Main.hs
  Simulation: src/Simulation.hs
module-template: ! 'module MODULE_NAME where

'
targets: {}
